# Generated by Django 5.2 on 2025-05-06 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlumniPortal', '0002_remove_event_attendees_event_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='summary',
            field=models.TextField(blank=True, help_text='A short summary or excerpt of the article (optional).', null=True),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='content',
            field=models.TextField(help_text='The main content of the news article.'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='image',
            field=models.ImageField(blank=True, help_text='An optional image to accompany the news article.', null=True, upload_to='news_images/'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='published_date',
            field=models.DateTimeField(blank=True, help_text="The date and time when the article was or will be published. If status is 'Published' and this is blank, it will be set to now.", null=True),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='slug',
            field=models.SlugField(blank=True, help_text='A unique slug for the news article URL (will be auto-generated if left blank).', max_length=220, unique=True),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', help_text='The current status of the news article (e.g., Draft, Published).', max_length=10),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
